import '@/scss/main.scss';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import AuthModal from '@/components/auth-modal';
import NotifyProvider from '@/providers/notify.provider';
import CartProvider from '@/providers/cart';
import LayoutWrapper from './layout-wrapper';
import { ConfigProvider } from 'antd';

const robotoSlab = Roboto_Slab({
  weight: ['400', '500', '600', '700', '800'],
  style: 'normal',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={robotoSlab.className}
        suppressHydrationWarning={true}>
        <LayoutWrapper>
          <AntdRegistry>
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: 'red',
                },
                components: {
                  Spin: {
                    dotSizeLG: 36,
                  },
                },
              }}>
              <NotifyProvider>
                <CartProvider>
                  <AuthModal />
                  {children}
                </CartProvider>
              </NotifyProvider>
            </ConfigProvider>
          </AntdRegistry>
        </LayoutWrapper>
      </body>
    </html>
  );
}
